### ISSUE TITLE
Start to learn React 

### ISSUE THREAD

**Issue by Mvitimin** [Mvitimin/React_study_project#2]
#### codepen 설정

![image](https://github.com/Mvitimin/React_study_project/assets/125615921/a9a87250-514c-47cd-a302-eabc9ce32e93)

```js
class App extends React.Component {
  state = {
    btn_color: 'button-red'
  };
  
  onclick = (event) => {
    this.setState({
      btn_color: 'button-grey'
    })
  }
  
  render() {
    return(
      <div>
        <button 
          onClick={this.onClick}
          className={this.state.btn.color}>
          Clieck Me!
        </button>
      </div>
    )
  }
}

ReactDOM.render(
  <App />,
  docuemnt.querySelector('#root')
)
```

```html
<div id='root' />
````

```css
.button-red {
  background-color: red;
  color: white;
 
}

.button-grey {
  background-color: grey;
  color: white;
}
```
